// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace AuctionSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Models.AuctionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuctionItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentPrice = 50.00m,
                            Description = "An old vintage clock.",
                            EndTime = new DateTime(2025, 9, 15, 19, 54, 11, 34, DateTimeKind.Local).AddTicks(6903),
                            StartPrice = 50.00m,
                            Title = "Vintage Clock"
                        },
                        new
                        {
                            Id = 2,
                            CurrentPrice = 100.00m,
                            Description = "A beautiful antique vase.",
                            EndTime = new DateTime(2025, 9, 13, 19, 54, 11, 34, DateTimeKind.Local).AddTicks(6927),
                            StartPrice = 100.00m,
                            Title = "Antique Vase"
                        });
                });

            modelBuilder.Entity("Models.Bid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("AuctionItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BidderName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuctionItemId");

                    b.ToTable("Bids");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 60.00m,
                            AuctionItemId = 1,
                            BidderName = "Alice",
                            CreatedAt = new DateTime(2025, 9, 8, 17, 54, 11, 34, DateTimeKind.Local).AddTicks(7227)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 70.00m,
                            AuctionItemId = 1,
                            BidderName = "Bob",
                            CreatedAt = new DateTime(2025, 9, 8, 18, 54, 11, 34, DateTimeKind.Local).AddTicks(7231)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 120.00m,
                            AuctionItemId = 2,
                            BidderName = "Charlie",
                            CreatedAt = new DateTime(2025, 9, 8, 16, 54, 11, 34, DateTimeKind.Local).AddTicks(7296)
                        });
                });

            modelBuilder.Entity("Models.Bid", b =>
                {
                    b.HasOne("Models.AuctionItem", "AuctionItem")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuctionItem");
                });

            modelBuilder.Entity("Models.AuctionItem", b =>
                {
                    b.Navigation("Bids");
                });
#pragma warning restore 612, 618
        }
    }
}
